V24 a 52 point calculation
InfoSec-Agent/InfoSec-Agent pull request #170
Opened 2024-05-07 14:43 UTC by Wouter99

2024-05-21 10:32 UTC, dvlpr-Kemi requested changes

2024-05-21 10:32 UTC, dvlpr-Kemi commented on backend/gamification/gamification.go
> +func PointCalculation(gs GameState, securityChecks []func() checks.Check) (GameState, error) {
What this function does can also be done partially inside the scan function. Right now, this function will once again loop over the scan.SecurityChecks and run the functions, which is unnecessary. Instead, you can pass the results of the scan to this function and then loop over each result and query the severity and go from there. This saves another loop of the scan.SecurityChecks slice.

2024-05-21 10:32 UTC, dvlpr-Kemi commented on backend/gamification/gamification.go
> +		result.ResultID = 0
This overwrites the ResultID the check has, so each check now gets a ResultID of 0.

2024-05-21 10:32 UTC, dvlpr-Kemi commented on backend/gamification/gamification.go
> +		db, err := sql.Open("sqlite", "reporting-page/database.db")
The database does not need to be opened for each check, open it before the loop, and close it in a defer.

2024-05-21 10:32 UTC, dvlpr-Kemi commented on backend/gamification/gamification.go
> +		db, err := sql.Open("sqlite", "reporting-page/database.db")
The path is incorrect, which does not allow you to query anything. I believe it needs to be "../../reporting-page/database.db".

2024-05-21 10:39 UTC, olafboekholt requested changes
Coverage van database package is nog relatief laag, maar volgens mij zijn die functies alleen verplaatst en heb je niks toegevoegd in wat nu in de database package staat, dus deze pr is daar niet de plek voor om dat op te lossen lijkt me.
Zie verder wel mijn comment over de coverage van de gamification package verder in de review.

2024-05-21 10:39 UTC, olafboekholt commented on backend/gamification/gamification.go
> +func PointCalculation(gs GameState, securityChecks []func() checks.Check) (GameState, error) {
Je geeft nu de lijst met functies mee, waardoor je als het ware opnieuw een scan uitvoert. Ik denk dat het beter is als je als parameter de lijst van checkresult objecten hebt, met de resultaten van een scan. Dan voer je hier niet nog een keer alle checks uit, en dan kan je ook makkelijker testcases maken, van speciefieke scenarios binnen checkresults. Coverage is van wat ik nu zie in golang rond de 40%, dit kan dan makkelijker omhoog door specifieke resultaten mee te geven.

2024-05-21 10:39 UTC, olafboekholt commented on backend/gamification/gamification.go
> +	case (gs.Points < 10):
De haakjes in de case zijn overal overbodig.
Ik had eig wel verwacht dat de linter dit soort dingen zou oppakken, daar moet ik zelf misschien ff naar kijken dan.

2024-05-27 07:15 UTC, Wouter99 commented
For now i resolved the issues . The testing coverage is not better than before though , this is something i can work on in another pull request if you agree .

2024-05-27 08:08 UTC, olafboekholt approved these changes

2024-05-27 08:08 UTC, dvlpr-Kemi approved these changes

2024-05-27 08:09 UTC, merged