V24A-675 add missing windows 10 screenshots
InfoSec-Agent/InfoSec-Agent pull request #320
Opened 2024-06-14 14:04 UTC by Wouter99

2024-06-15 11:18 UTC, SjaakRR commented on reporting-page/frontend/src/assets/images/windows-10/chrome-adblocker/chrome-adblocker-1.png
Maybe take screenshot on incognito or temporary profile to hide name?

2024-06-15 11:19 UTC, SjaakRR commented on reporting-page/frontend/src/assets/images/windows-10/chrome-adblocker/chrome-adblocker-2.png
Set chrome language to english?

2024-06-15 11:20 UTC, SjaakRR commented on reporting-page/frontend/src/assets/images/windows-10/chrome-adblocker/chrome-adblocker-3.png
Chrome to english?

2024-06-15 11:22 UTC, SjaakRR commented on reporting-page/frontend/src/assets/images/windows-10/edge-adblocker/edge-adblocker-2.png
language to english?

2024-06-15 11:26 UTC, SjaakRR commented on reporting-page/frontend/src/assets/images/windows-10/edge-adblocker/edge-adblocker-3.png
language to english?

2024-06-15 11:33 UTC, SjaakRR commented on reporting-page/frontend/src/databases/database.en-US.json
Are the text solutions still accurate for windows 11?

2024-06-15 12:28 UTC, SjaakRR requested changes

2024-06-15 12:28 UTC, SjaakRR commented on reporting-page/frontend/src/databases/database.en-US.json
Instead of changing the current solution, add the "SolutionWindows10" as used in other results and put the windows 10 specific changes there

2024-06-21 11:43 UTC, SjaakRR approved these changes

2024-06-24 08:23 UTC, RobSmink1 approved these changes

2024-06-24 08:24 UTC, merged